#!/bin/sh
CNAME="armx-docker"

# check if container is running
RUNNING=$(docker ps --format '{{.Names}}' | grep ${CNAME})
if [ "${RUNNING}" != "${CNAME}" ]
then
   echo "${CNAME}: container not running"
   exit
fi

if [ "$1" = "" ]
then
   echo "Usage: $0 remote <pid>|<process name>"
   echo "Use armxps to obtain remote processes"
   exit
else
   docker exec -it ${CNAME} /armx/run/armxkill $@
fi
