#!/bin/sh
CNAME="emux-docker"

# check if container is running
RUNNING=$(docker ps --format '{{.Names}}' | grep ${CNAME})
if [ "${RUNNING}" != "${CNAME}" ]
then
   echo "${CNAME}: container not running"
   exit
fi

if [ "$1" = "" ]
then
   echo "Usage: $0 remote <pid>|<process name>"
   echo "Use emuxps to obtain remote processes"
   exit
else
   docker exec -it ${CNAME} /emux/run/emuxkill $@
fi
