#!/bin/sh
CNAME="armx-docker"

# check if container is running
RUNNING=$(docker ps --format '{{.Names}}' | grep ${CNAME})
if [ "${RUNNING}" != "${CNAME}" ]
then
   echo "${CNAME}: container not running"
   exit
fi

docker exec -it ${CNAME} ssh root@192.168.100.2
