#!/bin/sh

OWNERNAME="therealsaumil"
IMAGENAME="emux"
TAGNAME="10-2021"
VOL="harambe"

# check if the volume exists, otherwise refuse to build. It doesn't
# matter really, but nice to ensure that the volume is built, to prevent
# later errors.

CHECKVOL=$(docker volume inspect ${VOL} -f '{{.Name}}')
if [ "$CHECKVOL" != "$VOL" ]
then
   echo "Docker volume $VOL needs to be created."
   echo "Please run ./build-emux-volume first."
   exit
fi

docker build -t $OWNERNAME/$IMAGENAME:$TAGNAME -f Dockerfile-emux .
