#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# EMUX by Saumil Shah
# https://emux.exploitlab.net/

OWNERNAME="therealsaumil"
IMAGENAME="emux"
TAGNAME="04-2025"
VOL="harambe"

# check if the volume exists, otherwise refuse to build. It doesn't
# matter really, but nice to ensure that the volume is built, to prevent
# later errors.

CHECKVOL=$(docker volume inspect ${VOL} -f '{{.Name}}')
if [ "$CHECKVOL" != "$VOL" ]
then
   echo "Docker volume $VOL needs to be created."
   echo "Please run ./build-emux-volume first."
   exit
fi

DOCKER_BUILDKIT=1 docker build -t $OWNERNAME/$IMAGENAME:$TAGNAME \
                               -f Dockerfile-emux .
