#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# EMUX (formerly ARMX) by Saumil Shah
# https://emux.exploitlab.net/

CNAME="emux-docker"

# check if container is running
RUNNING=$(docker ps --format '{{.Names}}' | grep ${CNAME})
if [ "${RUNNING}" != "${CNAME}" ]
then
   echo "${CNAME}: container not running"
   exit
fi

if [ "$1" = "" ]
then
   docker exec -e EMUXDOCKERSHELL=1 -it ${CNAME} /bin/bash
else
   docker exec -it ${CNAME} $@
fi
