#!/bin/bash
#
# Script to invoke gdbserver on the ARM-X instance and attach
# multi-arch gdb to the remote gdbserver
#
# Requires a parameter - pid or process name

gdb="gdb-multiarch"

if [ "$1" = "" ]
then
   echo "Usage: $0 remote <pid>|<process name>"
   echo "Use armxps to obtain remote processes"
   exit
fi

if [[ "$1" =~ ^[0-9]+$ ]]
then
   attach="--attach $1"
else
   attach="--attach \\\`pidof $1\\\`"
fi

source /armx/run/checkarmx
ARMXDEVICE=$(</tmp/armxrunning)
source /armx/run/parseini /armx/$ARMXDEVICE/config
ROOTFSPATH="/armx/$ARMXDEVICE/$ROOTFS"

$gdb -q \
   -ex="target remote | ssh -p 22222 -T root@192.168.100.2 gdbserver - $attach" \
   -ex="set sysroot target:$ROOTFSPATH"

