#!/bin/bash
#
# Script to check if we can access the ARM-X instance
#
# include in other scripts using "source /armx/run/checkarmx"

ping -W 1 -c 1 192.168.100.2 > /dev/null
if [ $? -ne 0 ]
then
   echo "ARM-X instance not running / reachable"
   exit
fi
