#!/bin/bash
#
# utility to quickly hide files by prepending a leading dot
# to their names.

if [ "$1" = "" ]
then
   echo "Usage: $0 <file1> [file2] ..."
   exit
fi

while [ "$1" != "" ]
do
   FILENAME=$(basename $1)
   FILEDIR=$(dirname $1)
   OUTFILE=$(echo "${FILENAME}" | sed -e 's/^\([^\.].*\)$/\.\1/')

   if [ "${FILENAME}" = "${OUTFILE}" ]
   then
      echo "skipping $FILEDIR/$FILENAME = $FILEDIR/$OUTFILE"
   else
      echo "hide $FILEDIR/$FILENAME -> $FILEDIR/$OUTFILE"
      mv "$FILEDIR/$FILENAME" "$FILEDIR/$OUTFILE"
   fi
   shift
done
