#!/bin/bash
#
# Loads the key, value pairs from the nvram.ini file into
# the emulated nvram

if [ "$1" = "" ]
then
   echo "Syntax: loadnvram <ini file>"
else
   echo "Loading nvram from $1"
   while IFS='=' read key value
   do
      echo "${key}='${value}'"
      nvram set ${key}="${value}"
   done <<< "$(cat "$1" | sed -e 's/#.*//g')"
fi

