#!/bin/bash
#
# Starts up the chroot'ed environment after mount binding
# /proc, /sys and /dev

echo ${RANDOMIZE_VA_SPACE} > /proc/sys/kernel/randomize_va_space

if [ "$LEGACY_VA_LAYOUT" != "" ]
then
   echo ${LEGACY_VA_LAYOUT} > /proc/sys/vm/legacy_va_layout
fi

if [ "$ID" = "" ]
then
   echo "Environment variables not set"
   exit
fi

NEWROOT="/armx/${ID}/${ROOTFS}"

mount --bind /proc ${NEWROOT}/proc
mount --bind /sys ${NEWROOT}/sys

# Mount the /dev tree only if the
# flag mount_dev_tree=1 is set
if [ "$MOUNTDEVTREE" = "1" ]
then
   mount --bind /dev ${NEWROOT}/dev
fi

# copy the libs to be LD_PRELOADed into ${NEWROOT}/.armx

DOTARMX="${NEWROOT}/.armx"

if [ ! -x ${DOTARMX} ]
then
   mkdir -p ${DOTARMX}
   chmod 755 ${DOTARMX}
fi
rm -f ${DOTARMX}/*.so

if [ "$PRELOADDIR" != "" ]
then
   PRELOADLIBS=""
   for lib in ${PRELOADDIR}/*.so
   do
      cp ${lib} ${DOTARMX}
      libfile=$(basename ${lib})
      PRELOADLIBS="/.armx/${libfile}:${PRELOADLIBS}"
   done
fi

# if invoked as a shell, don't overwrite
# /.armx/armxinit. instead use /.armx/armxshell

if [ "$1" != "shell" ]
then
   INITPATH="/.armx/armxinit"
else
   INITPATH="/.armx/armxshell"
fi

# If run-chroot is invoked with "shell" as a command line argument
# then simply drop to /bin/sh after chroot. Don't run the initcommands

echo "#!/bin/sh" > ${NEWROOT}${INITPATH}
if [ "$PRELOADDIR" != "" ]
then
   echo "export LD_PRELOAD=${PRELOADLIBS}" >> ${NEWROOT}${INITPATH}
fi

if [ "$1" != "shell" ]
then
   echo "${INITCOMMANDS}" | sed -e 's/^"//' -e 's/"$//' -e 's/;/\n/g' >> ${NEWROOT}${INITPATH}
   echo ">>> Starting ${ID}"
   log ">>> Starting ${ID}"
else
   echo "/bin/sh" >> ${NEWROOT}${INITPATH}
fi

chmod 755 ${NEWROOT}${INITPATH}
log "[+] Contents of $INITPATH\n$(cat ${NEWROOT}${INITPATH})"

echo "[+] chroot $NEWROOT $INITPATH"
log "[+] chroot $NEWROOT $INITPATH"

if [ "$ARMXLOGFILE" ]
then
   script -a -f -c "chroot ${NEWROOT} ${INITPATH}" ${ARMXLOGFILE}
else
   chroot ${NEWROOT} ${INITPATH}
fi
