#!/bin/bash
#
# Support functions for ARMX

ARMXDEBUGLOG="armxdebug.log"
QEMUCONSOLELOG="qemuconsole.log"

log () {
   if [ "$ARMXLOGFILE" ]
   then
      echo "$*" >> $ARMXLOGFILE
   fi
}

fatalerror () {
   echo "Fatal Error: $*"
   if [ "$ARMXLOGFILE" ]
   then
      echo "Fatal Error: $*"
   fi
   /armx/run/armxhalt
   exit
}

check_if_logging_required () {
   if [ -f /armx/run/debug ]
   then
      LOGPATH=$(cat /armx/run/debug | head -1)
      if [ ! -d ${LOGPATH} ]
      then
         LOGPATH="/armx/run/logs"
      fi
      export ARMXLOGFILE="${LOGPATH}/${ARMXDEBUGLOG}"
      export CONSOLELOGFILE="${LOGPATH}/${QEMUCONSOLELOG}"
   fi
}

new_log () {
   if [ -f "${ARMXLOGFILE}" ]
   then
      rm -f "${ARMXLOGFILE}"
      touch "${ARMXLOGFILE}"
   fi

   if [ -f "${CONSOLELOGFILE}" ]
   then
      rm -f "${CONSOLELOGFILE}"
      touch "${CONSOLELOGFILE}"
   fi
}

check_armx_volume_permissions() {
   if [ "$(stat -c '%U:%G' /armx/devices)" != "r0:r0" ]
   then
      echo "Setting permissions for /armx"
      sudo chown -R r0:r0 /armx
   fi
}

uncompress_qemu_roms () {
   # uncompress /armx/share/qemu.tar.bz2
   # when we are running for the first time
   echo "Uncompressing ROMs"
   if [ ! -d /armx/share/qemu/ ]
   then
      tar -C /armx/share -jxvf /armx/share/qemu.tar.bz2
   fi
}

uncompress_hostfs () {
   # uncompress /armx/hostfs/hostfs.ext2.bz2
   # when we are running for the first time
   echo "Uncompressing hostfs"
   if [ ! -f /armx/hostfs/hostfs.ext2 ]
   then
      bzip2 -dk /armx/hostfs/hostfs.ext2.bz2
   fi
}
