#!/bin/bash
#
# Support functions for ARMX

ARMXDEBUGLOG="armxdebug.log"
QEMUCONSOLELOG="qemuconsole.log"
DEBUGINDICATOR="/armx/debuglogs"

log () {
   if [ "$ARMXLOGFILE" ]
   then
      echo "$*" >> $ARMXLOGFILE
   fi
}

fatalerror () {
   echo "Fatal Error: $*"
   if [ "$ARMXLOGFILE" ]
   then
      echo "Fatal Error: $*"
   fi
   /armx/run/armxhalt
   exit
}

check_if_logging_required () {
   if [ -f ${DEBUGINDICATOR} ]
   then
      DEBUGLOGS=$(cat ${DEBUGINDICATOR} | grep '=' | grep -v '#' | head -1 \
                                        | sed -e 's/^ *//' -e 's/ *$//' -e 's/ *= */=/' -e 's/\/$//')
      if [ "${DEBUGLOGS}" != "" ]
      then
         echo "[+] Logging enabled"
         LOGPATH=$(echo ${DEBUGLOGS} | cut -d'=' -f2)
         if [ ! -d ${LOGPATH} ]
         then
            echo "[+] Creating log directory ${LOGPATH}"
            mkdir -p "${LOGPATH}"
         fi
         export ARMXLOGFILE="${LOGPATH}/${ARMXDEBUGLOG}"
         export CONSOLELOGFILE="${LOGPATH}/${QEMUCONSOLELOG}"
         echo "[+] ARMX Debug log - ${ARMXLOGFILE}"
         echo "[+] QEMU Console log - ${QEMUCONSOLELOG}"
      fi
   fi
}

new_log () {
   if [ -f "${ARMXLOGFILE}" ]
   then
      rm -f "${ARMXLOGFILE}"
      touch "${ARMXLOGFILE}"
   fi

   if [ -f "${CONSOLELOGFILE}" ]
   then
      rm -f "${CONSOLELOGFILE}"
      touch "${CONSOLELOGFILE}"
   fi
}

check_armx_volume_permissions() {
   if [ "$(stat -c '%U:%G' /armx/devices)" != "r0:r0" ]
   then
      echo "Setting permissions for /armx"
      sudo chown -R r0:r0 /armx
   fi
}

uncompress_qemu_roms () {
   # uncompress /armx/share/qemu.tar.bz2
   # when we are running for the first time
   echo "Uncompressing ROMs"
   if [ ! -d /armx/share/qemu/ ]
   then
      tar -C /armx/share -jxvf /armx/share/qemu.tar.bz2
   fi
}

uncompress_hostfs () {
   # uncompress /armx/hostfs/hostfs.ext2.bz2
   # when we are running for the first time
   echo "Uncompressing hostfs"
   if [ ! -f /armx/hostfs/hostfs.ext2 ]
   then
      bzip2 -dk /armx/hostfs/hostfs.ext2.bz2
   fi
}
