#!/bin/bash
#
# Script to kill -9 / killall -9 remote process(es)
#
# Requires a parameter - pid or process name

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# EMUX by Saumil Shah
# https://emux.exploitlab.net/

if [ "$1" = "" ]
then
   echo "Usage: $0 remote <pid>|<process name>"
   echo "Use emuxps to obtain remote processes"
   exit
fi

if [[ "$1" =~ ^[0-9]+$ ]]
then
   cmd="kill -9 $1"
else
   cmd="killall -9 $1"
fi

source /emux/run/checkemux
ssh -p 22222 -T root@192.168.100.2 "$cmd"
