#!/bin/bash
#
# Script to invoke gdbserver on the EMUX instance and attach
# multi-arch gdb to the remote gdbserver
#
# Requires a parameter - pid or process name

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# EMUX by Saumil Shah
# https://emux.exploitlab.net/

gdb="gdb-multiarch"
pscmd="pgrep -x"

if [ "$1" = "" ]
then
   echo "Usage: $0 remote <pid>|<process name>"
   echo "Use emuxps to obtain remote processes"
   exit
fi

if [[ "$1" =~ ^[0-9]+$ ]]
then
   attach="--attach $1"
else
   attach="--attach \\\`${pscmd} $1\\\`"
fi

source /emux/run/checkemux
EMUXDEVICE=$(</tmp/emuxrunning)
source /emux/run/parseini /emux/$EMUXDEVICE/config
ROOTFSPATH="/emux/$EMUXDEVICE/$ROOTFS"

$gdb -q \
   -ex="target remote | ssh -p 22222 -T root@192.168.100.2 gdbserver - $attach" \
   -ex="set sysroot target:$ROOTFSPATH"
