#!/bin/bash
#
# Script to shutdown the running EMUX instance

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# EMUX by Saumil Shah
# https://emux.exploitlab.net/

source /emux/run/checkemux
rm -f /tmp/emuxrunning
ssh -p 22222 -T root@192.168.100.2 "/usr/sbin/emuxhalt"
echo "Waiting for 10 seconds"
sleep 10
echo "q" | socat - TCP:127.0.0.1:55555
killall -9 ssh
