#!/bin/bash
#
# utility to quickly hide files by prepending a leading dot
# to their names.

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# EMUX by Saumil Shah
# https://emux.exploitlab.net/

if [ "$1" = "" ]
then
   echo "Usage: $0 <file1> [file2] ..."
   exit
fi

while [ "$1" != "" ]
do
   FILENAME=$(basename $1)
   FILEDIR=$(dirname $1)
   OUTFILE=$(echo "${FILENAME}" | sed -e 's/^\([^\.].*\)$/\.\1/')

   if [ "${FILENAME}" = "${OUTFILE}" ]
   then
      echo "skipping $FILEDIR/$FILENAME = $FILEDIR/$OUTFILE"
   else
      echo "hide $FILEDIR/$FILENAME -> $FILEDIR/$OUTFILE"
      mv "$FILEDIR/$FILENAME" "$FILEDIR/$OUTFILE"
   fi
   shift
done
