#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# EMUX by Saumil Shah
# https://emux.exploitlab.net/

emuxdir=$(dirname $0)
source ${emuxdir}/../run/utils
check_if_logging_required

log "[+] ${EMUX} parseini config"
source ${emuxdir}/../run/parseini config

log "[+] ${EMUX} run-chroot shell"
source ${emuxdir}/../run/run-chroot shell
