#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# EMUX by Saumil Shah
# https://emux.exploitlab.net/

emuxdir=$(dirname $0)
source ${emuxdir}/../run/utils
check_if_logging_required

echo $$ > /tmp/emuxstarted

log "[+] ${EMUX} parseini config"
source ${emuxdir}/../run/parseini config

log "[+] ${EMUX} loadnvram $NVRAM"
source ${emuxdir}/../run/loadnvram "$NVRAM"

log "[+] ${EMUX} run-chroot"
source ${emuxdir}/../run/run-chroot
