#!/bin/bash

emuxdir=$(dirname $0)
source ${emuxdir}/../run/utils
check_if_logging_required

log "[+] ${EMUX} parseini config"
source ${emuxdir}/../run/parseini config

log "[+] ${EMUX} run-chroot shell"
source ${emuxdir}/../run/run-chroot shell
