#!/bin/bash
#
# Utility script to take a flashmem.bin file, pad it up to 128MB
# and split it into 2 x 64MB files flash0.bin and flash1.bin

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# EMUX (formerly ARMX) by Saumil Shah
# https://emux.exploitlab.net/

if [ "$1" = "" ]
then
   echo "Usage: $0 flashmem.bin"
   exit
fi

output="flashmem.bin"
total_bytes=$(wc -c < ${output})
echo "Total bytes: ${total_bytes}"

if [ ${total_bytes} -le 134217728 ]
then
   difference=$(( 134217728 - ${total_bytes} ))
   pad_blocks=$(( $difference / 4096 ))
   echo "Appending ${difference} bytes as padding"
   dd if=/dev/zero of=padding bs=4096 count=${pad_blocks}
   cat padding >> ${output}
   rm -f padding
fi

echo "Creating 2 x 64MB flash memory files"
split -a 1 -b 64m ${output} flash
mv flasha flash0.bin
mv flashb flash1.bin
rm -f ${output}
echo "Done"
ls -s flash*.bin

