#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# EMUX by Saumil Shah
# https://emux.exploitlab.net/

if [ -f /tmp/emuxrunning ]
then
   ssh -p 22222 root@192.168.100.2
   # Sometimes the terminal goes insane
   stty sane
else
   echo "EMUX doesn't seem to be running. Have you run the 'launcher' yet?"
fi
