#!/bin/bash
#
# ARM-X QEMU Launcher
#
# By Saumil Shah
# The Exploit Laboratory
#
# requires dialog to be installed

source /armx/run/utils
uncompress_qemu_roms
uncompress_hostfs
check_if_logging_required
new_log

source /armx/run/parsedevices

hostfs=/armx/hostfs/hostfs.ext2

fundialog=${fundialog=dialog}

declare -a choices

j=0

for i in $(seq 0 $((count - 1)))
do
   choices[$j]=$i
   choices[$((j + 1))]=${descs[$i]}
   j=$((j + 2))
done

x=`$fundialog --stdout --clear --cancel-label "Quit" \
   --backtitle "ARM-X - The Versatile ARM IoT Device Emulator" \
   --menu "ARM-X Launcher" 0 0 0 "${choices[@]}"`

status=$?
clear

if [ $status -ne 0 ]
then
   exit
fi

cpu=""
dtb=""

if [ "${cpus[$x]}" != "" ]
then
   cpu="-cpu ${cpus[$x]}"
fi

if [ "${dtbs[$x]}" != "" ]
then
   dtb="-dtb /armx/dtb/${dtbs[$x]}"
fi

append=${bootargs[$x]}

qemucmd="/armx/run/${qemus[$x]} -M ${machines[$x]} ${cpu} -m ${mems[$x]} -kernel /armx/${ids[$x]}/kernel/${kernels[$x]} ${dtb} -drive file=${hostfs},${drives[$x]} ${flashargs[$x]} -append \"$append\" -net ${nics[$x]} -net tap,ifname=tap0,script=no,downscript=no ${customs[$x]} -nographic"
log "[+] QEMU Launch Command"
log "${qemucmd}"

# if the emulated device uses flash memory files and they don't exist,
# they need to be created, otherwise QEMU won't run

log "[+] Checking if flash memory files need to be created for ${ids[$x]}"
if [ "${flashfile[$x]}" != "" ]
then
   flashfile0="${flashfile[$x]}0.bin"
   flashfile1="${flashfile[$x]}1.bin"
   if [ ! -f ${flashfile0} ] || [ ! -f  ${flashfile1} ]
   then
      log "[+] flash memory files not found"
      log "Creating ${flashfile0}"
      mkdir -p $(dirname ${flashfile0})
      dd if=/dev/zero of=${flashfile0} bs=1M count=64
      log "Creating ${flashfile1}"
      dd if=/dev/zero of=${flashfile1} bs=1M count=64
   else
      log "[+] ${flashfile0} exists"
      log "[+] ${flashfile1} exists"
   fi
else
   log "[+] mtdparts not present"
fi

cp /armx/run/run-init-template /armx/${ids[$x]}/run-init
cp /armx/run/run-binsh-template /armx/${ids[$x]}/run-binsh

echo ${ids[$x]} > /tmp/armxrunning

if [ "$CONSOLELOGFILE" ]
then
   script -a -f -c "${qemucmd}" ${CONSOLELOGFILE}
else
   eval "$qemucmd"
fi
