#!/bin/bash
#
# Parses the devices file

declare -a ids qemus machines cpus dtbs mems kernels drives bootargs nics descs
count=0

DEVICES="/armx/devices"

while IFS=',' read ID QEMU MACHINE CPU DTB MEM KERNEL DRIVE BOOTARGS NIC DESC
do
   if [ "$ID" != "" ]
   then
      ids[$count]=$ID
      qemus[$count]=$QEMU
      machines[$count]=$MACHINE
      cpus[$count]=$CPU
      dtbs[$count]=$DTB
      mems[$count]=$MEM
      kernels[$count]=$KERNEL
      drives[$count]=$DRIVE
      bootargs[$count]="$BOOTARGS ARMX=$ID"
      nics[$count]=$NIC
      descs[$count]=$DESC
      count=$((count + 1))
   fi
done <<< "$(cat "${DEVICES}" | sed -e 's/#.*//g')"
