#!/bin/bash
#
# Parses the devices file

source /armx/run/utils

declare -a ids qemus machines cpus dtbs mems kernels qemuopts drives bootargs nics nets customs descs
declare -A qmachine qdrives qbootargs qnics qnet qcustoms

DEVICES="/armx/devices"
QEMUOPTS="/armx/qemuopts"
DEFAULT_NET="tap,ifname=tap0,script=no,downscript=no"

log "[+] Parsing ${QEMUOPTS}"

while IFS=',' read QMACHINE QDRIVE QBOOTCMD QNIC QNET QCUSTOM
do
   if [ "$QMACHINE" != "" ]
   then
      qmachine[$QMACHINE]=$QMACHINE
      qdrives[$QMACHINE]=$QDRIVE
      qbootargs[$QMACHINE]=$QBOOTCMD
      qnics[$QMACHINE]=$QNIC
      if [ "$QNET" == "" ]
      then
         QNET=$DEFAULT_NET
      fi
      qnet[$QMACHINE]=$QNET
      qcustoms[$QMACHINE]=$QCUSTOM

      log "$QMACHINE|${qbootargs[$QMACHINE]}|${qdrives[$QMACHINE]}|${qbootargs[$QMACHINE]}|${qnics[$QMACHINE]}|${qnet[$QMACHINE]}|${qcustoms[$QMACHINE]}"
   fi
done <<< "$(cat "${QEMUOPTS}" | sed -e 's/#.*//g')"

log "[+] Parsing ${DEVICES}"

count=0
while IFS=',' read ID QEMU MACHINE CPU DTB MEM KERNEL QOPTS DESC
do
   if [ "$ID" != "" ]
   then
      ids[$count]=$ID
      qemus[$count]=$QEMU
      machines[$count]=$MACHINE
      cpus[$count]=$CPU
      dtbs[$count]=$DTB
      mems[$count]=$MEM
      kernels[$count]=$KERNEL
      drives[$count]=${qdrives[$QOPTS]}
      bootargs[$count]="${qbootargs[$QOPTS]} ARMX=$ID"
      nics[$count]=${qnics[$QOPTS]}
      nets[$count]=${qnet[$QOPTS]}
      descs[$count]=$DESC
      customs[$count]=${qcustoms[$QOPTS]}

      log "${ids[$count]}|${qemus[$count]}|${machines[$count]}|${cpus[$count]}|${dtbs[$count]}|${mems[$count]}|${kernels[$count]}|${drives[$count]}|${bootargs[$count]}|${nics[$count]}|${nets[$count]}|${descs[$count]}"

      count=$((count + 1))
   fi
done <<< "$(cat "${DEVICES}" | sed -e 's/#.*//g')"
