#!/bin/bash
#
# Support functions for ARMX

LOGFILENAME="/armx/run/logs/armxdebug.log"
CONSOLELOG="/armx/run/logs/qemuconsole.log"

log () {
   if [ "$ARMXLOGFILE" ]
   then
      echo "$*" >> $ARMXLOGFILE
   fi
}

check_if_logging_required () {
   if [ -f /armx/run/debug ]
   then
      export ARMXLOGFILE="$LOGFILENAME"
      export CONSOLELOGFILE="$CONSOLELOG"
   fi
}

new_log () {
   if [ -f "$LOGFILENAME" ]
   then
      rm -f "$LOGFILENAME"
      touch "$LOGFILENAME"
   fi

   if [ -f "$CONSOLELOG" ]
   then
      rm -f "$CONSOLELOG"
      touch "$CONSOLELOG"
   fi
}

uncompress_qemu_roms () {
   # uncompress /armx/share/qemu.tar.bz2
   # when we are running for the first time
   echo "Uncompressing ROMs"
   if [ ! -d /armx/share/qemu/ ]
   then
      tar -C /armx/share -jxvf /armx/share/qemu.tar.bz2
   fi
}

uncompress_hostfs () {
   # uncompress /armx/hostfs/hostfs.ext2.bz2
   # when we are running for the first time
   echo "Uncompressing hostfs"
   if [ ! -f /armx/hostfs/hostfs.ext2 ]
   then
      bzip2 -d /armx/hostfs/hostfs.ext2.bz2
   fi
}
