#!/bin/bash
#
# Support functions for ARMX

LOGFILENAME="/armx/run/logs/armxdebug.log"
CONSOLELOG="/armx/run/logs/qemuconsole.log"

log () {
   if [ "$ARMXLOGFILE" ]
   then
      echo "$*" >> $ARMXLOGFILE
   fi
}

check_if_logging_required () {
   if [ -f /armx/run/debug ]
   then
      export ARMXLOGFILE="$LOGFILENAME"
      export CONSOLELOGFILE="$CONSOLELOG"
   fi
}

new_log () {
   if [ -f "$LOGFILENAME" ]
   then
      rm -f "$LOGFILENAME"
      touch "$LOGFILENAME"
   fi

   if [ -f "$CONSOLELOG" ]
   then
      rm -f "$CONSOLELOG"
      touch "$CONSOLELOG"
   fi
}

uncompress_qemu_roms () {
   # uncompress /armx/share/qemu.zip
   # when we are running for the first time
   if [ ! -d /armx/share/qemu/ ]
   then
      unzip /armx/share/qemu.zip -d /armx/share/
   fi
}
